"""Rename delete_at to marked_for_deletion_at

Revision ID: d4453a8a4c2c
Revises: 
Create Date: 2025-11-18 17:49:12.247140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4453a8a4c2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_for_deletion_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('delete_at')

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marked_for_deletion_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('delete_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('marked_for_deletion_at')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('marked_for_deletion_at')

    # ### end Alembic commands ###
